<?php return array (
  'DEV1_KEY1' => 'Name',
  'DEV2_KEY1' => 'Name',
  'DEV3_KEY1' => 'Name',
  'DEV4_KEY1' => 'Name',
  'DEV5_KEY1' => 'Name',
  'DEV6_KEY1' => 'Name',
  'DEV7_KEY1' => 'Name',
  'DEV8_KEY1' => 'Name',
  'SRV_NAME' => 'localhost',
  'SRV_IP' => '192.168.1.9',
  'SRV_PORT' => '9997',
  'STARTED' => false,
  'STARTEDDEV1' => false,
  'STARTEDDEV2' => false,
  'STARTEDDEV3' => false,
  'STARTEDDEV4' => false,
  'STARTEDDEV5' => false,
  'STARTEDDEV6' => false,
  'STARTEDDEV7' => false,
  'STARTEDDEV8' => false,
);