<?php return array (
  'KART1' => 'Name',
  'KART2' => 'Name',
  'KART3' => 'Name',
  'KART4' => 'Name',
  'KART5' => 'Name',
  'KART6' => 'Name',
  'KART7' => 'Name',
  'KART8' => 'Name',
  'STARTEDKART1' => false,
  'STARTEDKART2' => false,
  'STARTEDKART3' => false,
  'STARTEDKART4' => false,
  'STARTEDKART5' => false,
  'STARTEDKART6' => false,
  'STARTEDKART7' => false,
  'STARTEDKART8' => false,
  'STARTED' => false,
  'SRV_NAME' => 'localhost',
  'SRV_IP' => '192.168.1.7',
  'SRV_PORT' => '9997',
); ?>